#namespace enjin.sdk.shared.GetBalances
#import enjin.sdk.shared.Balance
#import enjin.sdk.shared.PaginationInput

#arg filter BalanceFilter
#arg pagination PaginationInput {page:1,limit:100}

query {
    result: Balances(
        filter: $filter,
        pagination: $pagination
    ) {
        items {
            ...Balance
        }
        cursor {
            ...PaginationCursor
        }
    }
}
