name: GitHub Pages

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          doxyfile-path: DOXYFILE

      - name: Deploy To Latest
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: html
          target-folder: sdk/latest
