#namespace enjin.sdk.project.AuthProject

#arg id Int!
#arg secret String!

query {
    result: AuthProject(
        id: $id,
        secret: $secret
    ) {
        accessToken
        expiresIn
    }
}
