#namespace enjin.sdk.shared.Token

#arg tokenIdFormat TokenIdFormat
#arg withTokenBlocks Boolean false
#arg withCreator Boolean false
#arg withMeltDetails Boolean false
#arg withMetadata Boolean false
#arg withMetadataURI Boolean false
#arg withSupplyDetails Boolean false
#arg withTransferSettings Boolean false
#arg withTokenVariantMode Boolean false
#arg withTokenVariants Boolean false
#arg withVariantMetadata Boolean false

fragment Token on EnjinToken {
    id(format: $tokenIdFormat)
    name
    blockHeight @include(if: $withTokenBlocks)
    creator @include(if: $withCreator)
    firstBlock @include(if: $withTokenBlocks)
    meltFeeRatio @include(if: $withMeltDetails)
    meltFeeMaxRatio @include(if: $withMeltDetails)
    meltValue @include(if: $withMeltDetails)
    metadata @include(if: $withMetadata)
    metadataURI @include(if: $withMetadataURI)
    nonFungible
    reserve @include(if: $withSupplyDetails)
    supplyModel @include(if: $withSupplyDetails)
    circulatingSupply @include(if: $withSupplyDetails)
    mintableSupply @include(if: $withSupplyDetails)
    totalSupply @include(if: $withSupplyDetails)
    transferable @include(if: $withTransferSettings)
    transferFeeSettings @include(if: $withTransferSettings) {
        type
        tokenId
        value
    }
    variantMode @include(if: $withTokenVariantMode)
    variants @include(if: $withTokenVariants) {
        id
        tokenId
        variantMetadata @include(if: $withVariantMetadata)
        usageCount
        createdAt
        updatedAt
    }
    createdAt
    updatedAt
}
