#namespace enjin.sdk.shared.Token

#arg tokenIdFormat TokenIdFormat
#arg withStateData Boolean false
#arg withConfigData Boolean false
#arg withTokenBlocks Boolean false
#arg withCreator Boolean false
#arg withMeltDetails Boolean false
#arg withMetadata Boolean false
#arg withMetadataURI Boolean false
#arg withSupplyDetails Boolean false
#arg withTransferSettings Boolean false
#arg withTokenVariantMode Boolean false
#arg withTokenVariants Boolean false
#arg withVariantMetadata Boolean false

fragment Token on Token {
    id(format: $tokenIdFormat)
    name
    stateData @include(if: $withStateData) {
        nonFungible
        creator @include(if: $withCreator)
        blockHeight @include(if: $withTokenBlocks)
        firstBlock @include(if: $withTokenBlocks)
        reserve @include(if: $withSupplyDetails)
        supplyModel @include(if: $withSupplyDetails)
        circulatingSupply @include(if: $withSupplyDetails)
        mintableSupply @include(if: $withSupplyDetails)
        totalSupply @include(if: $withSupplyDetails)
    }
    configData @include(if: $withConfigData) {
        meltFeeRatio @include(if: $withMeltDetails)
        meltFeeMaxRatio @include(if: $withMeltDetails)
        meltValue @include(if: $withMeltDetails)
        metadataURI @include(if: $withMetadataURI)
        transferable @include(if: $withTransferSettings)
        transferFeeSettings @include(if: $withTransferSettings) {
            type
            tokenId
            value
        }
    }
    variantMode @include(if: $withTokenVariantMode)
    variants @include(if: $withTokenVariants) {
        id
        tokenId
        variantMetadata @include(if: $withVariantMetadata)
        usageCount
        createdAt
        updatedAt
    }
    createdAt
    updatedAt
}
