#namespace enjin.sdk.shared.Transaction

#arg withMeta Boolean false
#arg withBlockchainData Boolean false
#arg withEncodedData Boolean false
#arg withTokenData Boolean false
#arg withSignedTxs Boolean false
#arg withError Boolean false
#arg withNonce Boolean false
#arg withState Boolean false
#arg withReceipt Boolean false

fragment Transaction on Transaction {
    id
    transactionId
    title @include(if: $withMeta)
    contract @include(if: $withMeta)
    type
    icon @include(if: $withMeta)
    value @include(if: $withTokenData)
    retryState @include(if: $withState)
    state @include(if: $withState)
    accepted @include(if: $withState)
    blockchainData @include(if: $withBlockchainData) {
        encodedData @include(if: $withEncodedData)
        signedTransaction @include(if: $withSignedTxs)
        signedBackupTransaction @include(if: $withSignedTxs)
        signedCancelTransaction @include(if: $withSignedTxs)
        receipt @include(if: $withReceipt)
        error @include(if: $withError)
        nonce @include(if: $withNonce)
    }
    tokenId @include(if: $withTokenData)
    createdAt
    updatedAt
}
